#!/usr/bin/env bash
# Steps 1-4 of the downstream chain for one Q-Former arm.
# See QFORMER_实验手册.md §3.4.
#
#   scripts_qformer_downstream.sh <ARM> <CHECKPOINT_BASENAME> <DEVICE_ORDINAL>
#
# --queries 32 is load-bearing: both build_qformer_bridge_cache and
# observation_kl_precheck default to 16 and nothing validates the value against
# the checkpoint. qk_norm is deliberately NOT passed -- the loader reads it from
# the checkpoint metadata, which is the only source that cannot drift.
#
# Written out in full rather than generated by sed. A sed rewrite of a sibling
# script once replaced a backslash-continued line with an empty one, which
# terminated the command early and silently launched a training run with argparse
# defaults -- 16 queries instead of 32, accumulate 8 instead of 4. It ran nine
# minutes before anyone noticed. Edit this file directly.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
ARM="$1"
CKPT="$2"
DEV="cuda:$3"
D="${QFORMER_BRIDGE_DIR:-$ROOT/outputs/instruct_bridge/v9-instruct-pca20k-balanced-xbar}"
MODEL="${QWEN35_MODEL:-$ROOT/models/Qwen3.5-9B}"
L="${QFORMER_LOG_DIR:-$ROOT/outputs/logs/p1}"

test -f "$D/$CKPT" || { echo "missing checkpoint: $D/$CKPT" >&2; exit 1; }
mkdir -p "$L"

# See scripts_qformer_train_arm.sh for why `set -u` has to be relaxed here.
set +u
source /mnt/data/public_tools/miniconda3/etc/profile.d/conda.sh
conda activate "${QFORMER_CONDA_ENV:-qwen-vl}"
set -u

cd "$ROOT"
export TOKENIZERS_PARALLELISM=false

echo "=== [$ARM] on $DEV  ckpt=$CKPT  $(date '+%F %T') ==="

echo "--- 1/4 state cache ---"
python -u -m experiments.state_tokenizer.build_qformer_bridge_cache \
  --xbar-dir "$D/wma-xbar-fitcorpus-axtree" \
  --teacher-dir "$D/wma-teacher-fitcorpus" \
  --checkpoint "$D/$CKPT" --model "$MODEL" \
  --output "$D/cache-$ARM.npz" \
  --queries 32 --qformer-layers 4 --device "$DEV" \
  --validation-fraction 0.2 --seed 35

echo "--- 2/4 retrieval head ---"
python -u -m experiments.state_tokenizer.train_retrieval_bridge \
  --cache "$D/cache-$ARM.npz" --output "$D/head-$ARM.pt" --device "$DEV"

# Diagnostic only; benchmark-specific ranking behavior is not a method gate.
echo "--- 3/4 head_recall diagnostic ---"
python -u -m experiments.state_tokenizer.head_recall \
  --head "$D/head-$ARM.pt" --cache "$D/cache-$ARM.npz" \
  --split validation --device cpu \
  --output "$L/hr-$ARM.json"

# 48 observations, not the trainer's inline 24: the two orderings disagree, and
# have done so twice. Only the 48-observation figure is comparable across arms.
echo "--- 4/4 fidelity gap, 48 observations, held-out probe P4 ---"
python -u -m experiments.state_tokenizer.observation_kl_precheck \
  --xbar-dir "$D/wma-xbar-fitcorpus-axtree" --checkpoint "$D/$CKPT" \
  --model "$MODEL" --queries 32 \
  --probe P4 --observations 48 --max-new-tokens 96 --seed 35 \
  --device "$DEV" --output "$L/final-$ARM.json"

echo "=== [$ARM] done  $(date '+%F %T') ==="
